import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  ShoppingBag,
  Plus,
  CheckCircle2,
  Trash2,
  Sparkles,
  PackageCheck,
} from "lucide-react";
import { ShoppingItem, Category, FoodItem } from "../types";
import { getExpiryStatus } from "../data/initialData";

interface ShoppingListScreenProps {
  shoppingItems: ShoppingItem[];
  foodItems: FoodItem[];
  onToggleItem: (id: string) => void;
  onAddItem: (newItem: Omit<ShoppingItem, "id">) => void;
  onDeleteItem: (id: string) => void;
  onClearCompleted: () => void;
  onGenerateSmartList: () => void;
  onMoveBoughtToInventory: () => void;
}

const CATEGORIES: Category[] = [
  "Vegetables",
  "Fruits",
  "Dairy",
  "Meat",
  "Frozen",
  "Snacks",
  "Drinks",
  "Bakery",
  "Pantry",
];

export const ShoppingListScreen: React.FC<ShoppingListScreenProps> = ({
  shoppingItems,
  foodItems,
  onToggleItem,
  onAddItem,
  onDeleteItem,
  onClearCompleted,
  onGenerateSmartList,
  onMoveBoughtToInventory,
}) => {
  const [name, setName] = useState("");
  const [category, setCategory] = useState<Category>("Pantry");
  const [quantity, setQuantity] = useState("1 pack");
  const [estimatedPrice, setEstimatedPrice] = useState("3.50");

  const handleAddSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;

    onAddItem({
      name: name.trim(),
      category,
      quantity: quantity.trim() || "1 item",
      estimatedPrice: parseFloat(estimatedPrice) || 2.50,
      completed: false,
      isAutoGenerated: false,
    });

    setName("");
    setQuantity("1 pack");
    setEstimatedPrice("3.50");
  };

  // Calculations
  const pendingItems = shoppingItems.filter((i) => !i.completed);
  const completedItems = shoppingItems.filter((i) => i.completed);

  const totalEstimatedCost = shoppingItems.reduce(
    (sum, item) => sum + (item.completed ? 0 : item.estimatedPrice),
    0
  );

  // Identify missing ingredients or expired items from food inventory that need restocking
  const restockSuggestions = foodItems.filter(
    (item) => getExpiryStatus(item.expiryDate) === "expired"
  );

  return (
    <div className="space-y-6 pb-12">
      {/* HEADER BANNER */}
      <div className="bg-[#0F172A] text-white p-6 rounded-[32px] border border-slate-800 shadow-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-[#22C55E] mb-1">
            Household Provisioning
          </p>
          <h2 className="text-3xl font-serif italic text-white">Shopping List</h2>
          <p className="text-xs text-slate-400 mt-1">
            {pendingItems.length} item{pendingItems.length === 1 ? "" : "s"} to buy • Est. Total:{" "}
            <span className="font-bold text-white">${totalEstimatedCost.toFixed(2)}</span>
          </p>
        </div>

        {/* Generate Smart List Button */}
        <button
          onClick={onGenerateSmartList}
          className="px-5 py-3 bg-[#22C55E] hover:bg-emerald-600 text-white font-bold text-xs uppercase tracking-widest rounded-full shadow-lg shadow-green-200 transition-all flex items-center justify-center gap-2 shrink-0 active:scale-95"
        >
          <Sparkles className="w-4 h-4" />
          <span>Generate Smart List</span>
        </button>
      </div>

      {/* ADD ITEM INPUT FORM */}
      <form
        onSubmit={handleAddSubmit}
        className="bg-white rounded-[32px] p-5 border border-slate-100 shadow-xs space-y-3"
      >
        <p className="text-xs font-bold uppercase tracking-widest text-slate-400 px-1">
          Add Custom Provision
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-12 gap-2">
          <input
            type="text"
            required
            placeholder="Item Name (e.g. Eggs, Almond Milk)..."
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="sm:col-span-4 px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-2xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-[#22C55E]"
          />

          <select
            value={category}
            onChange={(e) => setCategory(e.target.value as Category)}
            className="sm:col-span-3 px-3 py-2.5 bg-slate-50 border border-slate-200 rounded-2xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-[#22C55E]"
          >
            {CATEGORIES.map((cat) => (
              <option key={cat} value={cat}>
                {cat}
              </option>
            ))}
          </select>

          <input
            type="text"
            placeholder="Qty (e.g. 1 dozen)"
            value={quantity}
            onChange={(e) => setQuantity(e.target.value)}
            className="sm:col-span-2 px-3 py-2.5 bg-slate-50 border border-slate-200 rounded-2xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-[#22C55E]"
          />

          <div className="sm:col-span-3 flex gap-2">
            <div className="relative flex-1">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400">
                $
              </span>
              <input
                type="number"
                step="0.10"
                placeholder="Cost"
                value={estimatedPrice}
                onChange={(e) => setEstimatedPrice(e.target.value)}
                className="w-full pl-6 pr-2 py-2.5 bg-slate-50 border border-slate-200 rounded-2xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-[#22C55E]"
              />
            </div>

            <button
              type="submit"
              className="px-5 py-2.5 bg-slate-800 hover:bg-slate-900 text-white font-bold text-xs uppercase tracking-widest rounded-full shrink-0 flex items-center gap-1"
            >
              <Plus className="w-4 h-4" />
              <span className="hidden sm:inline">Add</span>
            </button>
          </div>
        </div>
      </form>

      {/* RESTOCK / MISSING INGREDIENTS BANNER */}
      {restockSuggestions.length > 0 && (
        <div className="bg-amber-50 border border-amber-200/80 rounded-[32px] p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 rounded-2xl bg-amber-100 text-[#F59E0B] flex items-center justify-center shrink-0">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-sm font-bold text-amber-900">
                Restock Needed ({restockSuggestions.length} Expired)
              </h4>
              <p className="text-xs text-amber-700">
                Items like {restockSuggestions.map((i) => i.name).join(", ")} are expired in your pantry.
              </p>
            </div>
          </div>
          <button
            onClick={onGenerateSmartList}
            className="px-4 py-2 bg-[#F59E0B] hover:bg-amber-600 text-white font-bold text-xs uppercase tracking-widest rounded-full shrink-0"
          >
            Auto Restock
          </button>
        </div>
      )}

      {/* SHOPPING CHECKLIST */}
      <div className="bg-white rounded-[32px] p-6 border border-slate-100 shadow-xs space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-slate-400">Pantry Checklist</p>
            <h3 className="text-lg font-serif italic text-slate-800">
              Shopping Checklist ({pendingItems.length} Remaining)
            </h3>
          </div>
          {completedItems.length > 0 && (
            <div className="flex items-center gap-2">
              <button
                onClick={onMoveBoughtToInventory}
                className="px-4 py-2 bg-green-50 hover:bg-green-100 text-[#22C55E] font-bold text-xs uppercase tracking-widest rounded-full border border-green-200 flex items-center gap-1.5"
                title="Add checked items to Food Inventory"
              >
                <PackageCheck className="w-3.5 h-3.5" />
                <span>Move to Pantry</span>
              </button>
              <button
                onClick={onClearCompleted}
                className="text-xs font-bold uppercase tracking-wider text-slate-400 hover:text-[#EF4444]"
              >
                Clear Checked
              </button>
            </div>
          )}
        </div>

        {/* Pending Items */}
        {pendingItems.length === 0 ? (
          <div className="text-center py-8">
            <CheckCircle2 className="w-12 h-12 text-[#22C55E] mx-auto mb-2" />
            <p className="text-base font-serif italic text-slate-800">Shopping list empty!</p>
            <p className="text-xs text-slate-400 mt-1">All items bought or none added yet.</p>
          </div>
        ) : (
          <div className="space-y-2">
            {pendingItems.map((item) => (
              <div
                key={item.id}
                className="flex items-center justify-between p-4 bg-slate-50 hover:bg-slate-100/80 rounded-2xl border border-slate-100 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    checked={item.completed}
                    onChange={() => onToggleItem(item.id)}
                    className="w-5 h-5 accent-[#22C55E] rounded-lg cursor-pointer"
                  />
                  <div>
                    <p className="font-bold text-slate-800 text-sm flex items-center gap-2">
                      <span>{item.name}</span>
                      {item.isAutoGenerated && (
                        <span className="bg-green-100 text-[#22C55E] text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                          Auto
                        </span>
                      )}
                    </p>
                    <p className="text-xs text-slate-400 font-medium">
                      {item.category} • Qty: {item.quantity}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span className="text-xs font-bold text-slate-700 bg-white px-3 py-1 rounded-full border border-slate-200">
                    Est. ${item.estimatedPrice.toFixed(2)}
                  </span>
                  <button
                    onClick={() => onDeleteItem(item.id)}
                    className="text-slate-300 hover:text-[#EF4444] p-1"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Completed Items Section */}
        {completedItems.length > 0 && (
          <div className="pt-4 border-t border-slate-100">
            <h4 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-3">
              Completed Items ({completedItems.length})
            </h4>
            <div className="space-y-2 opacity-70">
              {completedItems.map((item) => (
                <div
                  key={item.id}
                  className="flex items-center justify-between p-3 bg-slate-50 rounded-2xl border border-slate-100"
                >
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={item.completed}
                      onChange={() => onToggleItem(item.id)}
                      className="w-5 h-5 accent-[#22C55E] rounded-lg cursor-pointer"
                    />
                    <span className="line-through text-xs font-medium text-slate-500">
                      {item.name} ({item.quantity})
                    </span>
                  </div>
                  <span className="text-xs font-medium text-slate-400">
                    ${item.estimatedPrice.toFixed(2)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

