export type Category = 
  | "Vegetables"
  | "Fruits"
  | "Dairy"
  | "Meat"
  | "Frozen"
  | "Snacks"
  | "Drinks"
  | "Bakery"
  | "Pantry";

export type ExpiryStatus = "expired" | "expiring-soon" | "fresh";

export interface FoodItem {
  id: string;
  name: string;
  category: Category;
  quantity: string;
  purchaseDate: string; // YYYY-MM-DD
  expiryDate: string;   // YYYY-MM-DD
  storageLocation?: "Fridge" | "Pantry" | "Freezer";
  notes?: string;
  createdAt: number;
}

export interface Recipe {
  id?: string;
  recipeName: string;
  cookingTime: string;
  difficulty: "Easy" | "Medium" | "Hard";
  ingredientsUsed: string[];
  instructions: string[];
  nutritionTips: string;
  foodWasteTip: string;
  savedAt?: number;
}

export interface ShoppingItem {
  id: string;
  name: string;
  category: Category | "General";
  quantity: string;
  estimatedPrice: number; // e.g. 3.50
  completed: boolean;
  isAutoGenerated?: boolean;
}

export interface ActivityLog {
  id: string;
  title: string;
  description: string;
  timestamp: string;
  type: "add" | "consume" | "recipe" | "delete" | "shopping";
}

export interface UserProfile {
  name: string;
  email: string;
  avatarUrl: string;
  darkMode: boolean;
  notificationsEnabled: boolean;
  monthlySavings: number; // e.g. 145 ($)
  wastePreventedKg: number; // e.g. 12.8 (kg)
}

export type TabType = "home" | "inventory" | "recipes" | "shopping" | "profile";
