import { FoodItem, ShoppingItem, ActivityLog, UserProfile } from "../types";

// Helper to compute ISO date string offsetting from today
export function getRelativeDate(offsetDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split("T")[0];
}

// Calculate days remaining between today and expiry date
export function getDaysRemaining(expiryDateStr: string): number {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  const expiry = new Date(expiryDateStr);
  expiry.setHours(0, 0, 0, 0);
  
  const diffTime = expiry.getTime() - today.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

export function getExpiryStatus(expiryDateStr: string): "expired" | "expiring-soon" | "fresh" {
  const days = getDaysRemaining(expiryDateStr);
  if (days < 0) return "expired";
  if (days <= 3) return "expiring-soon";
  return "fresh";
}

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  {
    id: "item-1",
    name: "Fresh Whole Milk",
    category: "Dairy",
    quantity: "1 Gallon",
    purchaseDate: getRelativeDate(-5),
    expiryDate: getRelativeDate(2), // 2 days left -> Expiring Soon
    storageLocation: "Fridge",
    notes: "Opened 3 days ago",
    createdAt: Date.now() - 500000,
  },
  {
    id: "item-2",
    name: "Baby Spinach Leaves",
    category: "Vegetables",
    quantity: "250g Pack",
    purchaseDate: getRelativeDate(-4),
    expiryDate: getRelativeDate(1), // 1 day left -> Expiring Soon
    storageLocation: "Fridge",
    notes: "Great for salad or smoothie",
    createdAt: Date.now() - 400000,
  },
  {
    id: "item-3",
    name: "Chicken Breast Fillets",
    category: "Meat",
    quantity: "500g",
    purchaseDate: getRelativeDate(-7),
    expiryDate: getRelativeDate(-1), // Expired 1 day ago
    storageLocation: "Fridge",
    notes: "Check smell before cooking or freeze immediately",
    createdAt: Date.now() - 300000,
  },
  {
    id: "item-4",
    name: "Greek Yogurt Plain",
    category: "Dairy",
    quantity: "500g Tub",
    purchaseDate: getRelativeDate(-3),
    expiryDate: getRelativeDate(3), // 3 days left -> Expiring Soon
    storageLocation: "Fridge",
    createdAt: Date.now() - 250000,
  },
  {
    id: "item-5",
    name: "Crisp Gala Apples",
    category: "Fruits",
    quantity: "6 pcs",
    purchaseDate: getRelativeDate(-2),
    expiryDate: getRelativeDate(9), // Fresh
    storageLocation: "Pantry",
    createdAt: Date.now() - 200000,
  },
  {
    id: "item-6",
    name: "Aged Cheddar Cheese",
    category: "Dairy",
    quantity: "200g Block",
    purchaseDate: getRelativeDate(-6),
    expiryDate: getRelativeDate(12), // Fresh
    storageLocation: "Fridge",
    createdAt: Date.now() - 150000,
  },
  {
    id: "item-7",
    name: "Organic Orange Juice",
    category: "Drinks",
    quantity: "1 Liter",
    purchaseDate: getRelativeDate(-1),
    expiryDate: getRelativeDate(7), // Fresh
    storageLocation: "Fridge",
    createdAt: Date.now() - 100000,
  },
  {
    id: "item-8",
    name: "Sweet Garden Peas",
    category: "Frozen",
    quantity: "1 Bag (400g)",
    purchaseDate: getRelativeDate(-10),
    expiryDate: getRelativeDate(60), // Fresh
    storageLocation: "Freezer",
    createdAt: Date.now() - 50000,
  },
];

export const INITIAL_SHOPPING_ITEMS: ShoppingItem[] = [
  {
    id: "shop-1",
    name: "Whole Wheat Bread",
    category: "Bakery",
    quantity: "1 Loaf",
    estimatedPrice: 3.20,
    completed: false,
    isAutoGenerated: false,
  },
  {
    id: "shop-2",
    name: "Organic Eggs",
    category: "Dairy",
    quantity: "1 Dozen",
    estimatedPrice: 4.50,
    completed: false,
    isAutoGenerated: true,
  },
  {
    id: "shop-3",
    name: "Extra Virgin Olive Oil",
    category: "Pantry",
    quantity: "500ml",
    estimatedPrice: 8.90,
    completed: true,
    isAutoGenerated: false,
  },
  {
    id: "shop-4",
    name: "Fresh Avocados",
    category: "Fruits",
    quantity: "3 pcs",
    estimatedPrice: 4.00,
    completed: false,
    isAutoGenerated: true,
  }
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: "act-1",
    title: "Added Food Item",
    description: "Added 250g Baby Spinach Leaves to Fridge",
    timestamp: "10 mins ago",
    type: "add",
  },
  {
    id: "act-2",
    title: "Generated AI Recipe",
    description: "Created Spinach & Yogurt Dip recipe",
    timestamp: "1 hour ago",
    type: "recipe",
  },
  {
    id: "act-3",
    title: "Shopping List Updated",
    description: "Added Organic Eggs to restock list",
    timestamp: "3 hours ago",
    type: "shopping",
  },
];

export const INITIAL_PROFILE: UserProfile = {
  name: "Alex Morgan",
  email: "alex.morgan@freshkeeper.app",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
  darkMode: false,
  notificationsEnabled: true,
  monthlySavings: 185,
  wastePreventedKg: 14.2,
};
